eShopSolution.WebApp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShopSolution.ApiIntegration;
using eShopSolution.Utilities.Constants;
using eShopSolution.ViewModels.Sales;
using eShopSolution.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace eShopSolution.WebApp.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IOrderApiClient _orderApiClient;

        

        public CartController(IProductApiClient productApiClient, IOrderApiClient orderApiClient)
        {
            _productApiClient = productApiClient;
            _orderApiClient = orderApiClient;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Checkout()
        {
            return View(GetCheckoutViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel request)
        {
            var model = GetCheckoutViewModel();
            var orderDetails = new List<OrderDetailVm>();
            foreach (var item in model.CartItems)
            {
                orderDetails.Add(new OrderDetailVm()
                {
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Price,
                });
            }
            var checkoutRequest = new CheckoutRequest()
            {
                Address = request.CheckoutModel.Address,
                Name = request.CheckoutModel.Name,
                Email = request.CheckoutModel.Email,
                PhoneNumber = request.CheckoutModel.PhoneNumber,
                OrderDetails = orderDetails
            };
            //TODO: Add to API
            var check = await _orderApiClient.CreatOderDetail(checkoutRequest);
            if (check)
            {
                TempData["SuccessMsg"] = "Gửi phiếu mua hàng thành công, chúng tôi sẽ liên hệ sớm cho bạn";

            }
            else
            {
                TempData["ErrorMsg"] = "Gửi phiếu mua hàng thất bại, mong bạn kiểm tra lại thông tin";

            }
            return View(model);
        }

        [HttpGet]
        public IActionResult GetListItems()
        {
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);
            return Ok(currentCart);
        }

        public async Task<IActionResult> AddToCart(int id, int quantity = 1)
        {
            var product = await _productApiClient.GetById(id);

            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);

            if (currentCart.Any(x => x.ProductId == id))
            {
                quantity = currentCart.First(x => x.ProductId == id).Quantity + 1;
            }

            var cartItem = new CartItemViewModel()
            {
                ProductId = id,
                Description = product.Description,
                Image = product.ThumbnailImage,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity
            };

            currentCart.Add(cartItem);

            HttpContext.Session.SetString(SystemConstants.CartSession, JsonConvert.SerializeObject(currentCart));
            return Ok(currentCart);
        }

        public IActionResult UpdateCart(int id, int quantity)
        {
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);

            foreach (var item in currentCart)
            {
                if (item.ProductId == id)
                {
                    if (quantity == 0)
                    {
                        currentCart.Remove(item);
                        break;
                    }
                    item.Quantity = quantity;
                }
            }

            HttpContext.Session.SetString(SystemConstants.CartSession, JsonConvert.SerializeObject(currentCart));
            return Ok(currentCart);
        }

        private CheckoutViewModel GetCheckoutViewModel()
        {
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);
            var checkoutVm = new CheckoutViewModel()
            {
                CartItems = currentCart,
                CheckoutModel = new CheckoutRequest()
            };
            return checkoutVm;
        }
        public async Task<IActionResult> OrderOld()
        {

            var listProduct = await _productApiClient.getProductOldOrder();

            return View(listProduct);
        }
    }
}

eShopSolution.WebApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.WebApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopSolution.WebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShopSolution.ApiIntegration;
using eShopSolution.ViewModels.Catalog.Products;
using eShopSolution.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace eShopSolution.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient _categoryApiClient;

        public ProductController(IProductApiClient productApiClient, ICategoryApiClient categoryApiClient)
        {
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IActionResult> Detail(int id, string culture)
        {
            var product = await _productApiClient.GetById(id);
            var productStarts = await _productApiClient.getProductStartByProductId(id);

            return View(new ProductDetailViewModel()
            {
                Product = product,
                ProductStarts = productStarts
            });
        }
        [HttpPost]
        public async Task<IActionResult> Detail(ProductDetailViewModel request)
        {
            
            
            //TODO: Add to API
            var check = await _productApiClient.CreateProductStart(request.ProductStart);
            if (check.IsSuccessed)
            {
                TempData["SuccessMsg"] = "Gửi đánh giá thành công, cảm ơn bạn!";

            }
            else
            {
                if(check.Message != "")
                {
                    TempData["ErrorMsg"] = check.Message;

                }
                else
                {
                    TempData["ErrorMsg"] = "Gửi đánh giá thất bại, bạn kiểm tra lại thông tin!";

                }

            }
            var product = await _productApiClient.GetById(request.ProductStart.ProductId);
            var productStarts = await _productApiClient.getProductStartByProductId(request.ProductStart.ProductId);

            request.Product = product;
            request.ProductStarts = productStarts;
            return View(request);
        }

        public async Task<IActionResult> Category(int id, string culture, int page = 1)
        {
            var products = await _productApiClient.GetPagings(new GetManageProductPagingRequest()
            {
                CategoryId = id,
                PageIndex = page,
                LanguageId = culture,
                PageSize = 10
            });
            var category = await _categoryApiClient.GetById(id);
            return View(new ProductCategoryViewModel()
            {
                Category = category,
                Products = products
            }); ;
        }
        public async Task<IActionResult> GetAll(string culture ,string keyword, int page = 1, int categoryId = 0)
        {
            var products = await _productApiClient.GetPagings(new GetManageProductPagingRequest()
            {
                CategoryId = categoryId,
                PageIndex = page,
                LanguageId = culture,
                PageSize = 10,
                Keyword = keyword,
            });
            return View(new ProductPagingViewModel()
            {
                Products = products
            }); 
        }
    }
}

eShopSolution.WebApp/Views/Product/Category.cshtml
@model ProductCategoryViewModel

@{ ViewData["Title"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "" : " - " + _loc["Page"] + " " + Model.Products.PageIndex);
    ViewData["Description"] = Model.Category.Name + (Model.Products.PageIndex == 1 ? "" : " - " + _loc["Page"] + " " + Model.Products.PageIndex);
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture; }
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
@section styles {
    <link href="~/assets/pages/home/css/index.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
}
<ul class="breadcrumb">
    <li><a href="/">Trang chủ</a> <span class="divider">/&nbsp;</span></li>
    <li class="active">@Model.Category.Name</li>
</ul>
<h3> @Model.Category.Name <small class="pull-right"> 40 <localize>available products</localize> </small></h3>
<hr class="soft" />
<p>
    @Model.Category.Description
</p>
<hr class="soft" />
@*<form class="form-horizontal div-6">
    <div class="control-group">
        <label class="form-label"><localize>Sort By</localize> </label>
        <select>
            <option>Priduct name A - Z</option>
            <option>Priduct name Z - A</option>
            <option>Priduct Stoke</option>
            <option>Price Lowest first</option>
        </select>
    </div>
</form>*@

@*<div id="myTab" class="pull-right">
    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
</div>*@
<br class="clr" />

<div class="row prd1-right-items">



    @for (int idx = 0; idx < Model.Products.Items.Count; idx++)
    {

        var item = Model.Products.Items[idx];


<div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 item">
    <div class="thumbnail">

        <div class="cont-item">
            <a href="/@culture.Name/@_loc["products"]/@item.Id"><img src="@(Configuration["BaseAddress"] + item.ThumbnailImage[0])" alt="@item.Name" style="width: 100%; height: auto"></a>


        </div>
        <div class="button">
            <a class="btn btn-prd1-buynow hidden-xs hidden-sm btn-add-cart" data-id="@item.Id">
                Thêm vào giỏ
            </a>
            @*<a class="btn btn-prd1-heart addToWishList" href="javascript:void(0)" data-liked="false" data-action="transferCartToWishList" data-idproduct="713796"></a>*@
        </div>
        <div class="caption">
            <h3 class="type">@item.Name</h3>
            <h3 class="divider"></h3>
            <h3 class="name">
                <a class="btn" href="/@culture.Name/@_loc["products"]/@item.Id" localize-content>Xem chi tiết</a>
            </h3>

            <h3 class="color">@item.SeoAlias</h3>
            <h3 class="price">
                @item.Price.ToString()
            </h3>
        </div>

    </div>
</div>}
</div>
@await Component.InvokeAsync("Pager", Model.Products)
<br class="clr" />

eShopSolution.WebApp/Views/Product/Detail.cshtml
@model ProductDetailViewModel
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture;
}
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
@section styles {
    <link href="~/assets/pages/product/css/detail.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('.alert').fadeOut('slow');
        }, 1000);
    </script>
}
<ul class="breadcrumb">
    <li><a href="/"><localize>Home</localize></a> <span class="divider">/&nbsp;</span></li>
    <li class="active">@Model.Product.Name</li>
</ul>

<div class="row">
    <div id="gallery" class="col-6">
        <div class="row">
            @for (int index = 0; index < Model.Product.ThumbnailImage.Count(); index++)
            {
                <div class="col-6">
                    <div>
                        @{
                            var resultText = @index + 1;
                        }
                        Ảnh @resultText
                    </div>
                    <a href="@(Configuration["BaseAddress"] + Model.Product.ThumbnailImage[index])" title="@Model.Product.Name">
                        <img src="@(Configuration["BaseAddress"] + Model.Product.ThumbnailImage[index])" style="width:100%" alt="@Model.Product.Name" />
                    </a>
                </div>

            }
        </div>



        <div>
            Đánh giá:
            <span><i class="icon-star"></i></span>
        </div>
        <hr class="soft" />
        @if (TempData["ErrorMsg"] != null)
        {
            <span class="alert alert-danger">@TempData["ErrorMsg"]</span>
        }
        @if (TempData["SuccessMsg"] != null)
        {
            <span class="alert alert-success">@TempData["SuccessMsg"]</span>
        }
        <div>
            <form class="form-horizontal" action="/@culture/Product/Detail" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ProductStart.ProductId" value="@Model.Product.Id" />
                <div class="row g-3">
                   
                    <div class="col-md-6">
                        <label for="inputComment" class="form-label">Đánh giá</label>
                        <input type="text"  class="form-control" id="inputComment" asp-for="ProductStart.Comment" placeholder="Viết đánh giá ở đây">
                    </div>
                    <div class="col-md-3">
                        <label for="inputStart" class="form-label">Số sao</label>
                        <input type="number" class="form-control" id="inputStart" value="5" asp-for="ProductStart.Start" placeholder="Số sao cho sản phẩm">

                    </div>
                    <div class="col-md-3">
                        <label for="inputStart" class="form-label">Xác nhận</label>
                        <button type="submit" class="btn btn-large btn-primary">Gửi</button>

                    </div>
                </div>
               
            </form>
        </div>        
    </div>
    <div class="col-6">
        <h3 class="name-style">@Model.Product.Name</h3>
        <small>@Model.Product.Description</small>
        <hr class="soft" />
        <form class="qtyFrm ">
            @*method="post"  action="@Url.Action("AddToCart", "Cart", @Model.Product)"*@
            <label class="control-label">Giá: <span>@Model.Product.Price</span>VND</label>
            <div class="input-group row">
                <div class="col-3 m-auto">
                    <label class="control-label align-items-end ">Số lượng: </label>

                </div>
                <div class="col-2">
                    <input type="number" id="value_quantity" class="form-control" value="1" />
                </div>
                <div class="col-7">
                    <button type="submit" class=" btn btn-large btn-primary pull-right btn-add-cart " data-id="@Model.Product.Id"> <localize>Add to</localize> <i class=" icon-shopping-cart"></i></button>

                </div>
            </div>
        </form>

        <hr class="soft" />
        <h4>@Model.Product.Stock sản phẩm còn trong kho</h4>
        @*<form class="form-horizontal qtyFrm pull-right">
                <div class="control-group">
                    <label class="control-label"><span>Color</span></label>
                    <div class="controls">
                        <select class="span2">
                            <option>Black</option>
                            <option>Red</option>
                            <option>Blue</option>
                            <option>Brown</option>
                        </select>
                    </div>
                </div>
            </form>*@
        <hr class="soft clr" />
        <p>
            @Html.Raw(Model.Product.Details)
        </p>
        <a class="btn btn-small pull-right" href="#detail"><localize>More Details</localize></a>
        <br class="clr" />
        <a href="#" name="detail"></a>
        <hr class="soft" />
    </div>
    
</div>
<div class=" mt-5 mb-5">

    <div class="row  d-flex justify-content-center">

        <div class="col-md-8">

            <div class="headings d-flex justify-content-between align-items-center mb-3">
                @if (Model.ProductStarts.Count > 0) {
                    <h5>Tất cả đánh giá (@Model.ProductStarts.Count)</h5>

                @*<div class="buttons">

                    <span class="badge bg-white d-flex flex-row align-items-center">
                        <span class="text-primary">Comments "ON"</span>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>

                        </div>
                    </span>

                </div>*@
                }
            </div>

            @if (Model.ProductStarts.Count > 0)
            {
                @foreach (var item in Model.ProductStarts)
                {
                    <div class="card p-3 mb-3">

                        <div class="d-flex justify-content-between align-items-center">

                            <div class="user d-flex flex-row align-items-center">

                                <span><small class="font-weight-bold text-primary">@item.UserName: </small> <small class="font-weight-bold">@item.Comment</small></span>

                            </div>


                            <small>
                                @item.Start <span><i class="icon-star"></i></span></small>

                        </div>


                        @*<div class="action d-flex justify-content-between mt-2 align-items-center">

                            <div class="reply px-4">
                                text

                            </div>



                        </div>*@



                    </div>
                }
            }







        </div>

    </div>

</div>
<div>
    Chi tiết:
    <p>
        @Html.Raw(Model.Product.Details)
    </p>
</div>

eShopSolution.WebApp/Views/Product/GetAll.cshtml
@model ProductPagingViewModel

@{ ViewData["Title"] = "Danh sách sản phẩm";
    ViewData["Description"] =  (Model.Products.PageIndex == 1 ? "" : " - " + _loc["Page"] + " " + Model.Products.PageIndex);
    Layout = "~/Views/Shared/_Layout.cshtml";
    var culture = CultureInfo.CurrentCulture; }
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@inject LazZiya.ExpressLocalization.ISharedCultureLocalizer _loc;
@section styles {
    <link href="~/assets/pages/home/css/index.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
}
<ul class="breadcrumb">
    <li><a href="/">Trang chủ</a> <span class="divider">/</span></li>
</ul>
<hr class="soft" />

<form class="form-horizontal span6">
    <div class="control-group">
        <label class="control-label alignL"><localize>Sort By</localize> </label>
        <select>
            <option>Priduct name A - Z</option>
            <option>Priduct name Z - A</option>
            <option>Priduct Stoke</option>
            <option>Price Lowest first</option>
        </select>
    </div>
</form>
<br class="clr" />

<div class="row prd1-right-items">



    @for (int idx = 0; idx < Model.Products.Items.Count; idx++)
    {

        var item = Model.Products.Items[idx];


        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 item">
            <div class="thumbnail">

                <div class="cont-item">

                    <a href="/@culture.Name/@_loc["products"]/@item.Id"><img src="@(Configuration["BaseAddress"] + item.ThumbnailImage[0])" alt="@item.Name" style="width: 100%; height: auto"></a>


                </div>
                <div class="button">
                    <a class="btn btn-prd1-buynow hidden-xs hidden-sm btn-add-cart" data-id="@item.Id">
                        Thêm vào giỏ
                    </a>
                </div>
                <div class="caption">
                    <h3 class="type">@item.Name</h3>
                    <h3 class="divider"></h3>
                    <h3 class="name">
                        <a class="btn" href="/@culture.Name/@_loc["products"]/@item.Id" localize-content>Xem chi tiết</a>
                    </h3>
                    <h3 class="price">
                        @item.Price.ToString()
                    </h3>
                </div>

            </div>
        </div>}
</div>
@await Component.InvokeAsync("Pager", Model.Products)
<br class="clr" />